services:
  demo:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: Serves some tiles as a WMS for KMI.

globals:
  image:
    paletted: false

layers:
  - name: mapbox-light
    title: Mapbox light
    sources: [mapbox-light-cache]
  - name: mapbox-dark
    title: Mapbox dark
    sources: [mapbox-dark-cache]
  - name: mapbox-satellite
    title: Mapbox satellite
    sources: [mapbox-satellite-cache]
  - name: mapbox-streets-satellite
    title: Mapbox streets-satellite
    sources: [mapbox-streets-satellite-cache]
  - name: mapbox-emerald
    title: Mapbox emerald
    sources: [mapbox-emerald-cache]
  - name: mapbox-outdoors
    title: Mapbox outdoors
    sources: [mapbox-outdoors-cache]
  - name: mapbox-streets
    title: Mapbox streets
    sources: [mapbox-streets-cache]
  - name: sentinel-roads
    title: Sentinel Roads
    sources: [sentinel-roads-wms]
  - name: telstra-gcm-4g-3g
    title: Telstra GCM 4G 3G
    sources: [telstra-gcm-4g-3g-cache]
  - name: optus-gcm-4g-3g
    title: Optus GCM 4G 3G
    sources: [optus-gcm-4g-3g-cache]
  - name: vodafone-gcm-4g-3g
    title: Vodafone GCM 4G 3G
    sources: [vodafone-gcm-4g-3g-cache]

grids:
  GRID_TELSTRA:
    srs: EPSG:3857
    tile_size: [512, 512]
    origin: ul
    num_levels: 16
    min_res: 156543.03392800014
    max_res: 4.77731426794937



caches:
  mapbox-light-cache:
    sources: [mapbox-light-tile]
    grids: [GLOBAL_WEBMERCATOR]
    disable_storage: true
  mapbox-dark-cache:
    sources: [mapbox-dark-tile]
    grids: [GLOBAL_WEBMERCATOR]
    disable_storage: true
  mapbox-satellite-cache:
    sources: [mapbox-satellite-tile]
    grids: [GLOBAL_WEBMERCATOR]
    disable_storage: true
  mapbox-streets-satellite-cache:
    sources: [mapbox-streets-satellite-tile]
    grids: [GLOBAL_WEBMERCATOR]
    disable_storage: true
  mapbox-outdoors-cache:
    sources: [mapbox-outdoors-tile]
    grids: [GLOBAL_WEBMERCATOR]
    disable_storage: true
  mapbox-emerald-cache:
    sources: [mapbox-emerald-tile]
    grids: [GLOBAL_WEBMERCATOR]
    disable_storage: true
  mapbox-streets-cache:
    sources: [mapbox-streets-tile]
    grids: [GLOBAL_WEBMERCATOR]
    disable_storage: true
  telstra-gcm-4g-3g-cache:
    sources: [telstra-gcm-4g-3g-tile]
    grids: [GRID_TELSTRA]
    disable_storage: true
  optus-gcm-4g-3g-cache:
    sources: [optus-gcm-4g-3g-wms]
    grids: [GLOBAL_MERCATOR]
    disable_storage: true
    meta_size: [1, 1]
    meta_buffer: 0
  vodafone-gcm-4g-3g-cache:
    sources: [vodafone-gcm-4g-3g-wms]
    grids: [GLOBAL_MERCATOR]
    disable_storage: true
    meta_size: [1, 1]
    meta_buffer: 0

sources:
  mapbox-light-tile:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://api.mapbox.com/v4/mapbox.light/%(z)s/%(x)s/%(y)s.%(format)s?access_token=pk.eyJ1IjoiZHBhd2FzaSIsImEiOiJtVjY5WmlFIn0.whc76euXLk2PkyxOkZ5xlQ
  mapbox-dark-tile:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://api.mapbox.com/v4/mapbox.dark/%(z)s/%(x)s/%(y)s.%(format)s?access_token=pk.eyJ1IjoiZHBhd2FzaSIsImEiOiJtVjY5WmlFIn0.whc76euXLk2PkyxOkZ5xlQ
  mapbox-satellite-tile:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://api.mapbox.com/v4/mapbox.satellite/%(z)s/%(x)s/%(y)s.%(format)s?access_token=pk.eyJ1IjoiZHBhd2FzaSIsImEiOiJtVjY5WmlFIn0.whc76euXLk2PkyxOkZ5xlQ
  mapbox-streets-satellite-tile:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://api.mapbox.com/v4/mapbox.streets-satellite/%(z)s/%(x)s/%(y)s.%(format)s?access_token=pk.eyJ1IjoiZHBhd2FzaSIsImEiOiJtVjY5WmlFIn0.whc76euXLk2PkyxOkZ5xlQ
  mapbox-emerald-tile:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://api.mapbox.com/v4/mapbox.emerald/%(z)s/%(x)s/%(y)s.%(format)s?access_token=pk.eyJ1IjoiZHBhd2FzaSIsImEiOiJtVjY5WmlFIn0.whc76euXLk2PkyxOkZ5xlQ
  mapbox-outdoors-tile:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://api.mapbox.com/v4/mapbox.outdoors/%(z)s/%(x)s/%(y)s.%(format)s?access_token=pk.eyJ1IjoiZHBhd2FzaSIsImEiOiJtVjY5WmlFIn0.whc76euXLk2PkyxOkZ5xlQ
  mapbox-streets-tile:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://api.mapbox.com/v4/mapbox.streets/%(z)s/%(x)s/%(y)s.%(format)s?access_token=pk.eyJ1IjoiZHBhd2FzaSIsImEiOiJtVjY5WmlFIn0.whc76euXLk2PkyxOkZ5xlQ
  telstra-gcm-4g-3g-tile:
    type: tile
    grid: GRID_TELSTRA
    url: http://gcm.telstra.com.au/gisserver/rest/services/GCM_4G_3G_ns/MapServer/tile/%(z)s/%(y)s/%(x)s
    image:
       mode: RGBA
       transparent: true
    on_error: 
      404: 
        response: transparent
        cache: true

  optus-gcm-4g-3g-wms:
    type: wms
    supported_srs: ['EPSG:900913']
    req:
      url: http://www2.optus.com.au/geoserver/wms?
      layers: 'MBLITE_4G-10'
      transparent: true
      tiled: true
      format: 'image/gif'

  vodafone-gcm-4g-3g-wms:
    type: wms
    supported_srs: ['EPSG:900913']
    req:
      url: http://maps.vodafone.com.au/pdswms-vha44/cache?
      version: 'VODA-BYDATE-DATA-L1800,L2100,L850,U2100,U900,U850-BASE'
      layers: '[{"VISIBLE_NETWORKS":"VODA","MODE":"BYDATE","RENDER_AS":"DATA","FREQUENCIES":"L1800,L2100,L850,U2100,U900,U850","COVERAGE_CONFIGS":"BASE,ROAMING","DEVICE_CAP":"LTE","STAT_SET":"SVC_DATA_AVG","STAT_COLUMN":"","name":"VHA_COVERAGE_CLASS","theme":"vha_grid","visibility":true},{"name":"COVERAGE_CLIP_BOUNDARY","theme":"vha_grid","visibility":true}]'
      transparent: true
      renderset: 'vha_grid'
      styles: 'vha_cov_tile'
      format: 'image/gif'
    min_res: 4891.96981025128

  sentinel-roads-wms:
    type: wms
    supported_srs: ['EPSG:4326']
    req:
      url: http://sentinel.ga.gov.au/wmsconnector/com.esri.wms.Esrimap?
      layers: 1101,1100,1102,1104,1103,1140,1141,1170,1171,1172,1173
      transparent: true
    coverage:
      bbox: [113.15627999999998,-43.64304999905776,153.63857,-10.687579997555682]
      srs: 'EPSG:4326'
    image:
      transparent_color: '#ffffff'
      transparent_color_tolerance: 5
