[tool.poetry]
name = "dbcamapproxy"
version = "1.13.0"
description = "DBCA internal MapProxy service application"
authors = ["ASI <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
MapProxy = "1.13.0"
gevent = "21.1.2"
greenlet = "1.1.0"
Pillow = "8.2.0"
gunicorn = "20.1.0"
PyYAML = "5.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.6"]
build-backend = "poetry.masonry.api"
