[tool.poetry]
name = "dbcamapproxy"
version = "1.10.4"
description = "DBCA internal MapProxy service application"
authors = ["ASI <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
MapProxy = "1.13.0"
gevent = "20.12.1"
greenlet = "0.4.17"
Pillow = "8.0.1"
pyyaml = "5.3.1"
gunicorn = "20.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
