[tool.poetry]
name = "dbcamapproxy"
version = "1.14.0"
description = "DBCA internal MapProxy service application"
authors = ["ASI <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
MapProxy = "1.14.0"
gevent = "21.12.0"
greenlet = "1.1.2"
Pillow = "9.0.1"
gunicorn = "20.1.0"
PyYAML = "6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.13"]
build-backend = "poetry.masonry.api"
