[tool.poetry]
name = "dbcamapproxy"
version = "2.0.2"
description = "DBCA internal MapProxy service application"
authors = ["ASI <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.11"
mapproxy = "2.0.2"
pillow = "10.3.0"
gunicorn = "22.0.0"
pyyaml = "6.0.1"
pyproj = "3.6.1"
lxml = "5.2.2"
shapely = "2.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
