apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
resources:
  - ../../base
  - ingress.yaml
  - pdb.yaml
configMapGenerator:
  - name: mapproxy-configmap
    files:
      - mapproxy.yaml
      - seed.yaml
      - logging.ini
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      variant: uat
patches:
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
