apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapproxy-lock-data
spec:
  storageClassName: azurefile-csi-retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
