apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapproxy-cache-data
spec:
  storageClassName: azurefile-csi-premium-retain-zrs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
