apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapproxy-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: mapproxy
        image: ghcr.io/dbca-wa/mapproxy
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Australia/Perth"
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        startupProbe:
          httpGet:
            path: /demo/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /demo/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /demo/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 15
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: "Memory"
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
