apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapproxy-cache
spec:
  storageClassName: managed-csi-premium
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
